[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["zomes/coordinator/*", "zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = "0.3.2"
hdk = "0.2.2"
holochain = { version = "=0.2.2" }
serde = "1"
