[package]
name = "hc_zome_assemble_integrity"
version = "0.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_assemble_integrity"

[dependencies]
hdi = { workspace = true }

serde = { workspace = true }
